### ISSUE TITLE
The encoding of the main.c

### ISSUE THREAD

**Issue by yrabbit** [endurodave/C_StateMachine#1]
Git sees the main.c as binary blob and hexedit shows why: it's some UNICODE16 variant.
In its pure form, this file is not compiled with GCC. This is not a real problem, I can always recode it manually, just for your attention:)
![shot-0](https://user-images.githubusercontent.com/6075465/100675634-06bacc80-33b3-11eb-86bb-08e1540e8634.png)

**Comment by endurodave** [comment]
Should be fixed now.
