### ISSUE TITLE
Passing arugments to the STATE_MAP_ENTRIES that aren't void raises warnings

### ISSUE THREAD

**Issue by mcgdb** [endurodave/C_StateMachine#2]
Hello,

In the motor example, this warning is raised by GCC when passing the `MotorData*` to the function pointer contained within the array for holding the State Map.

`initialization of 'void (*)(SM_StateMachine *, void *)' from incompatible pointer type 'void (*)(SM_StateMachine *, MotorData *)'`

**Comment by endurodave** [comment]
Fixed compiler warnings.
